return {
    -- ██████  ███████  █████  ██   ██     ███████  ██████ ██████  ██ ██████  ████████ ███████ 
    -- ██   ██ ██      ██   ██ ██  ██      ██      ██      ██   ██ ██ ██   ██    ██    ██      
    -- ██████  █████   ███████ █████       ███████ ██      ██████  ██ ██████     ██    ███████ 
    -- ██      ██      ██   ██ ██  ██           ██ ██      ██   ██ ██ ██         ██         ██ 
    -- ██      ███████ ██   ██ ██   ██     ███████  ██████ ██   ██ ██ ██         ██    ███████ 
                              
    interact = 'ox_target', -- ox_target, interact or sleepless_interact 

    debugPoly = false,
    modelTimeout = 50000, -- If you get failed to load model errors, increase this value. 

    robberyEverywhere = false, -- You can rob houses anywhere. If you have skill system you can only rob houses depending on your level.

    noiseBar = {
        alertAmount = 40, -- The alarm will be activated and the police alerted when this value is reached.
        noiseAmountMultiplier = { -- Multipliers for noise generated by walking inside the house and firing weapons. Do not change this unless you know what you are doing.
            player = 10,
            weapon = {
                silenced = 20,
                normal = 100
            }
        },
    },

    startPed = {
        enabled = true, -- Enable the npc to start the house robbery mission
        useDialog = false, -- If true, it uses bl_dialog
        model = 'a_m_m_mlcrisis_01',
        blip = {
            enabled = false,
            sprite = 40,
            display = 4,
            scale = 0.6,
            colour = 11,
        },

        targetHouseBlip = {
            sprite = 364,
            display = 2,
            scale = 1.0,
            colour = 1,
        },
    },

    trader = {
        enabled = true, -- Enable the trader
        model = 'ig_beverly',
        blip = {
            enabled = false,
            sprite = 108,
            display = 4,
            scale = 0.6,
            colour = 28,
        },
    },

    progressBars = {
        breakIntoFurniture = {
            duration = 5000,
            label = 'Włamywanie...',
            position = 'bottom',
            useWhileDead = false,
            canCancel = true,
            disable = {
                car = true,
                move = true,
                combat = true
            },
            anim = {
                dict = 'anim@gangops@morgue@table@',
                clip = 'player_search'
            },
        },
        stealObject = {
            duration = 3000,
            label = 'Okradanie...',
            position = 'bottom',
            useWhileDead = false,
            canCancel = true,
            disable = {
                car = true,
                move = true,
                combat = true
            },
            anim = {
                dict = 'missexile3',
                clip = 'ex03_dingy_search_case_base_michael',
            },
        },
        tradeItems = {
            duration = 2000,
            position = 'bottom',
            label = 'Wymieniasz przedmioty...',   
            useWhileDead = false,
            canCancel = true,   
            disable = {
                car = true,
                move = true,
                combat = true
            },
            anim = {
                dict = 'misscarsteal4@actor',
                clip = 'actor_berating_loop'
            },
        }
    },        

    shellRobberyAlert = function(coords)
        TriggerServerEvent("mrg_houserobbery:piotreq:alert", coords)
        return -- Place your dispatch system export here
    end,

    iplRobberyAlert = function(coords)
        TriggerServerEvent("mrg_houserobbery:piotreq:alert", coords)
        return -- Place your dispatch system export here
    end,
}
