var language = "pl"; // default support for pl, en
// languages
if(language=="pl")
{
    var locales = {
        text_1: "Nie masz konta w naszym banku.",
        text_2: "Kliknij aby założyć konto",
        text_3: "Saldo Konta",
        text_4: "Wpłata",
        text_5: "Wypłata",
        text_6: "Przelew",
        text_7: "Konto bankowe",
        text_8: "W ekwipunku",
        text_9: "Historia",
        text_10: "Kwota",
        text_11: "Typ",
        text_12: "Data",
        text_13: "Przelew przychodzący",
        text_14: "Przelew wychodzący",
        text_15: "Wpłata",
        text_16: "Wypłata",
        text_17: "Opłacenie faktury",
        text_18: "Notatka:",
        text_19: "Wpłata środków",
        text_20: "Kwota",
        text_21: "Tytuł",
        text_22: "Wróć",
        text_23: "Wpłać",
        text_24: "Wypłata środków",
        text_25: "Wypłać",
        text_26: "Przelew",
        text_27: "Numer konta",
        text_28: "Przelej",
        text_29: "Typ transakcji",
        text_30: "Brak danych.",
        text_31: "Waluty",
        text_32: "Portfel krypto",
        text_33: "Sprzedaj",
        text_34: "Kup",
        text_35: "Przelej",
        text_36: "(Główne)",
        text_37: "Sprzedaż",
        text_38: "Kupno",
        text_39: "Transfer przychodzący",
        text_40: "Transfer wychodzący",
        text_41: "Sprzedaż kryptowaluty",
        text_42: "Ilość",
        text_43: "Wybierz kryptowalutę",
        text_44: "Brak kryptowaluty na sprzedaż.",
        text_45: "Sprzedaj",
        text_46: "Zakup kryptowaluty",
        text_47: "Kup",
        text_48: "Transfer kryptowaluty",
        text_49: "Portfel odbiorcy",
        text_50: "Transfer",
        text_51: "Brak kryptowaluty do transferu.",
        text_52: "Brak kryptowalut.",
        text_53: "Wybrane konto",
        text_54: "Wybrany portfel",
        text_55: "Ilość Transakcji",
        text_56: "SYSTEM",
        text_57: "Adresat",
        text_58: "Ostatnie akcje",
        text_59: "Waluta",
    }
}

if(language=="en")
{
    var locales = {
        text_1: "You don't have an account with our bank.",
        text_2: "Click to create an account",
        text_3: "Available funds:",
        text_4: "Deposit",
        text_5: "Withdrawal",
        text_6: "Transfer",
        text_7: "Bank account :: ",
        text_8: "In inventory: ",
        text_9: "Transaction history",
        text_10: "Amount",
        text_11: "Type/note",
        text_12: "Date",
        text_13: "Incoming transfer",
        text_14: "Outgoing transfer",
        text_15: "Deposit",
        text_16: "Withdrawal",
        text_17: "Payment of the invoice",
        text_18: "Note:",
        text_19: "Deposit funds",
        text_20: "Amount",
        text_21: "Description",
        text_22: "Back",
        text_23: "Deposit",
        text_24: "Cash withdrawal",
        text_25: "Withdraw",
        text_26: "Transfer",
        text_27: "Bank account number",
        text_28: "Transfer",
        text_29: "Transaction type:",
        text_30: "No data.",
        text_31: "Currency",
        text_32: "Crypto wallet :: ",
        text_33: "Sell",
        text_34: "Buy",
        text_35: "Transfer",
        text_36: "(main)",
        text_37: "Sale of cryptocurrency",
        text_38: "Buying cryptocurrency",
        text_39: "Incoming transfer",
        text_40: "Outgoing transfer",
        text_41: "Cryptocurrency sales",
        text_42: "Amount",
        text_43: "Select cryptocurrency",
        text_44: "No cryptocurrency for sale.",
        text_45: "Sell",
        text_46: "Purchasing cryptocurrency",
        text_47: "Buy",
        text_48: "Cryptocurrency transfer",
        text_49: "Recipients wallet",
        text_50: "Transfer",
        text_51: "No cryptocurrency to transfer.",
        text_52: "No cryptocurrencies.",
        text_53: "Selected account",
        text_54: "Selected wallet",
    }
}
