var language = "pl"; // default support for pl, en

// languages
if(language=="pl")
{
    var locales = {
        menu_button_finances: "Operacje finansowe",
        menu_button_desc_finances: "Wystaw fakturę lub sprawdź historie",
        menu_button_employees: "Pracownicy",
        menu_button_desc_employees: "Lista pracowników",
        menu_button_announcements: "Ogłoszenia",
        menu_button_desc_announcements: "Lista ogłoszeń i informacji",
        menu_button_stats: "Statystyki",
        menu_button_desc_stats: "Statystyki biznesu i personalne",
        menu_button_updates: "Ulepszenia",
        menu_button_desc_updates: "Rozbuduj swój biznes",
        menu_button_settings: "Ustawienia",
        menu_button_desc_settings: "Zarządzaj biznesem",
        menu_button_addInvoice: "Dodaj fakturę",
        finances_bank_amount: "Stan konta",
        finances_bank_number: "Numer konta",
        finances_bank_list: "Lista ostatnio wystawionych faktur/paragonów",
        finances_bank_list_name: "Kto wystawił",
        finances_bank_list_amount: "Kwota",
        finances_bank_list_desc: "Treść",
        finances_bank_list_date: "Data",
        employees_placeholder_search: "Wyszukaj pracownika",
        employees_button_add_employee: "Dodaj pracownika",
        employees_button_set_bonus: "Wypłać premie",
        employees_list_name: "Imię i nazwisko",
        employees_list_position: "Stanowisko",
        employees_list_time_work: "Czas pracy",
        employees_list_time_work_full: "Całkowity czas pracy",
        employees_list__actions: "Akcje",
        announcements_button_add_adv: "Dodaj ogłoszenie",
        announcements_button_delete_adv: "Usuń ogłoszenie",
        stats_header_text: "Twoje statystyki",
        stats_list_desc_position: "Twoje stanowisko",
        stats_list_desc_date: "Zatrudniony od",
        stats_list_desc_timework: "Czas pracy",
        stats_list_desc_invoices: "wystawionych faktur",
        stats_header_text2: "Statystyki biznesu",
        stats_list_desc_employees: "pracowników",
        stats_list_desc_dolars: "zarobionych dolarów",
        stats_list_desc_updates: "zakupionych ulepszeń",
        updates_text_need: "Wymagane ulepszenie",
        updates_text_price: "Koszt",
        updates_button_buy: "Kup ulepszenie",
        updates_haveUpdate: "Posiadane",
        settings_menu_setbonus: "Ustaw wysokość premii",
        settings_menu_setmenu: "Ustaw menu",
        settings_menu_permissions: "Ustaw dostęp w tablecie",
        settings_menu_bankaccount: "Ustaw dostęp do konta bankowego",
        addinvoice_placeholder_idplayer: "ID Gracza",
        addinvoice_placeholder_amount: "Kwota",
        addinvoice_placeholder_desc: "Opis",
        addinvoice_button_add: "Wystaw fakturę",
        addanno_placeholder_title: "Tytuł ogłoszenia",
        addanno_placeholder_desc: "Treść ogłoszenia",
        addanno_button_add: "Dodaj ogłoszenie",
        dropanno_confirm: "Czy na pewno chcesz usunąć ogłoszenie",
        dropanno_button: "Usuń",
        setbonus_list_position: "Stanowisko",
        setbonus_list_amount: "Wysokość premii($/h)",
        setbonus_list_actions: "Akcje",
        setmenu_placeholder_search: "Wyszukaj zestaw",
        setmenu_button_addkit: "Dodaj zestaw",
        setmenu_list_name: "Nazwa zestawu",
        setmenu_list_price: "Cena",
        setmenu_list_products: "Produkty",
        setmenu_list_actions: "Akcje",
        setmenu_list_noproducts: "Brak produktów",
        dropproduct_confirm: "Czy na pewno chcesz usunąć z menu",
        dropproduct_button: "Usuń",
        addnewkit_text_list: "Lista produktów",
        addnewkits_text_nameKit: "Nazwa zestawu",
        addnewkits_text_products: "Produkty w zestawie",
        addnewkits_text_noproducts: "Jeszcze nie dodałeś produktów",
        addnewkits_text_price: "Cena zestawu",
        addnewkits_button_add: "Dodaj zestaw",
        setpermissions_list_position: "Stanowisko",
        setpermissions_list_premissions: "Dostępy",
        setpermissions_list_actions: "Akcje",
        access_list_name: "Imię i nazwisko",
        access_list_premission: "Konto bankowe",
        access_list_actions: "Akcje",
        access_list_info: "Ma dostęp",
        access_list_button: "Nadaj dostęp",
        access_set_text: "Wybierz pracownika",
        access_button_text: "Nadaj dostęp do konta bankowego",
        setpermissions_list_nodata: "Brak dodatkowych uprawnień",
        addemployee_text_idplayer: "ID Gracza",
        addemployee_placeholder_idplayer: "Wpisz ID Gracza",
        addemployee_button_add: "Zatrudnij",
        payoutbonus_text_idplayer: "Wybierz pracownika",
        payoutbonus_text_hours: "Przepracowanych godzin",
        payoutbonus_text_money: "Do wypłaty",
        payoutbonus_button_payout: "Wypłać premię",
        dropemployee_text: "Czy na pewno chcesz zwolnić",
        dropemployee_button_drop: "Zwolnij",
        changepositionemployee_text_name: "Imię i nazwisko",
        changepositionemployee_text_position: "Aktualne stanowisko",
        changepositionemployee_text_new_position: "Nowe stanowisko",
        changepositionemployee_placeholder_position: "Wybierz nowe stanowisko",
        changepositionemployee_button_save: "Zapisz",
        editposition_placeholder_money: "Zarobek na godzine",
        editposition_button_save: "Zapisz",
        editpermissions_text_list: "Lista uprawnień",
        editpermissions_text_1: "Wystawianie faktur",
        editpermissions_text_2: "Stan konta",
        editpermissions_text_3: "Historia operacji finansowych",
        editpermissions_text_4: "Zatrudnianie pracowników",
        editpermissions_text_5: "Wypłacanie premii",
        editpermissions_text_6: "Zwalnianie pracowników",
        editpermissions_text_7: "Zmiana stanowiska pracownika",
        editpermissions_text_8: "Dodawanie ogłoszeń",
        editpermissions_text_9: "Usuwanie ogłoszeń",
        editpermissions_text_10: "Statystyki biznesu",
        editpermissions_text_11: "Zakup ulepszeń",
        editpermissions_text_12: "Zarządzanie wysokością premii",
        editpermissions_text_13: "Przeglądanie menu",
        editpermissions_text_15: "Dodawanie zestawów menu",
        editpermissions_text_16: "Usuwanie zestawów menu",
        editpermissions_text_17: "Zmiana dostępu pracowników",
        editpermissions_button_save: "Zapisz",
        editpermissions_no_permission: "Brak dodatkowych uprawnień",
        editpermissions_text_permissions: "Stanowisko",
        headers_text_finances: "Finanse",
        headers_text_employees: "Pracownicy",
        headers_text_announcements: "Ogłoszenia",
        headers_text_stats: "Statystyki",
        headers_text_updates: "Ulepszenia",
        headers_text_settings: "Ustawienia",
        headers_text_addInvoice: "Dodaj fakturę",
        headers_text_addAnno: "Dodaj ogłoszenie",
        headers_text_dropAnno: "Usuń ogłoszenie",
        headers_text_setBonus: "Ustaw wysokości premii",
        headers_text_setMenu: "Ustaw menu",
        headers_text_setPermissions: "Ustaw dostęp pracowników",
        headers_text_setAccessBank: "Ustaw dostęp do konta bankowego",
        headers_text_addEmployee: "Dodaj pracownika",
        headers_text_payoutBonus: "Wypłać premię",
        headers_text_dropEmployee: "Zwolnij pracownika",
        headers_text_changePositionEmployee: "Zmień stanowisko pracownika",
        headers_text_editPosition: "Edycja premii",
        headers_text_editPermissions: "Edycja uprawnień",
        headers_text_addNewProduct: "Dodaj produkt",
        headers_text_addNewKit: "Dodaj zestaw",
        headers_text_dropProduct: "Usuń zestaw",
        restart_timework: "Zresetuj czas pracy",
        headers_text_resetWorktime: "Reset czasu pracy",
        editpermissions_text_5_2: "Resetowanie czasu pracy",
        resettimework_text_confirm: "Czy na pewno chcesz zresetować czas pracy?",
        resettimework_button_confirm: "Tak, zresetuj",
        // update 29.04
        editpermissions_text_18: "Statystyki pracownika",
        stats_none: "Brak",
        stats_none2: "Statystyk",
        headers_text_employeeStats: "Statystyki",
        // update 18.07
        editpermissions_text_19: "Resetowanie statystyk pracownika",
        stats_reset_button: "Zresetuj statystyki",
        // update 04.09
        announcements_button_edit_adv: "Edytuj",
        headers_text_editAnno: "Edycja ogłoszenia",
        editanno_button: "Zapisz",
    }
}

if(language=="en")
{
    var locales = {
        menu_button_finances: "Financial operations",
        menu_button_desc_finances: "Issue an invoice or check your histories",
        menu_button_employees: "Employees",
        menu_button_desc_employees: "Employees list",
        menu_button_announcements: "Advertisements",
        menu_button_desc_announcements: "List of announcements and information",
        menu_button_stats: "Statistics",
        menu_button_desc_stats: "Business and personnel statistics",
        menu_button_updates: "Upgrades",
        menu_button_desc_updates: "Expand your business",
        menu_button_settings: "Settings",
        menu_button_desc_settings: "Manage your business",
        menu_button_addInvoice: "Add invoice",
        finances_bank_amount: "Account balance",
        finances_bank_number: "Account number",
        finances_bank_list: "List of recently issued invoices/receipts",
        finances_bank_list_name: "Who issued it",
        finances_bank_list_amount: "Amount",
        finances_bank_list_desc: "Content",
        finances_bank_list_date: "Date",
        employees_placeholder_search: "Search for employee",
        employees_button_add_employee: "Add employee",
        employees_button_set_bonus: "Pay Bonuses",
        employees_list_name: "Name and surname",
        employees_list_position: "Position",
        employees_list_time_work: "Working time",
        employees_list_time_work_full: "Total work time",
        employees_list__actions: "Actions",
        announcements_button_add_adv: "Add announcement",
        announcements_button_delete_adv: "Delete announcement",
        stats_header_text: "Your stats",
        stats_list_desc_position: "Your position",
        stats_list_desc_date: "Hired since",
        stats_list_desc_timework: "Worktime",
        stats_list_desc_invoices: "issued invoices",
        stats_header_text2: "Business Statistics",
        stats_list_desc_employees: "employees",
        stats_list_desc_dolars: "dollars earned",
        stats_list_desc_updates: "purchased upgrades",
        updates_text_need: "Improvement Required",
        updates_text_price: "Cost",
        updates_button_buy: "Buy Upgrade",
        updates_haveUpdate: "Owned",
        settings_menu_setbonus: "Set bonus amount",
        settings_menu_setmenu: "Set menu",
        settings_menu_permissions: "Set access on tablet",
        settings_menu_bankaccount: "Set access to bank account",
        addinvoice_placeholder_idplayer: "Player ID",
        addinvoice_placeholder_amount: "Amount",
        addinvoice_placeholder_desc: "Description",
        addinvoice_button_add: "Issue an invoice",
        addanno_placeholder_title: "Title of the advertisement",
        addanno_placeholder_desc: "Advertisement content",
        addanno_button_add: "Add ad",
        dropanno_confirm: "Are you sure you want to delete the ad",
        dropanno_button: "Delete",
        setbonus_list_position: "Position",
        setbonus_list_amount: "Bonus Amount($/h)",
        setbonus_list_actions: "Actions",
        setmenu_placeholder_search: "Search for set",
        setmenu_button_addkit: "Add kit",
        setmenu_list_name: "Set name",
        setmenu_list_price: "Price",
        setmenu_list_products: "Products",
        setmenu_list_actions: "Actions",
        setmenu_list_noproducts: "No products",
        dropproduct_confirm: "Are you sure you want to remove from the menu",
        dropproduct_button: "Delete",
        addnewkit_text_list: "Product List",
        addnewkits_text_nameKit: "Kit Name",
        addnewkits_text_products: "Products included",
        addnewkits_text_noproducts: "You haven't added products yet",
        addnewkits_text_price: "Kit Price",
        addnewkits_button_add: "Add kit",
        setpermissions_list_position: "Position",
        setpermissions_list_premissions: "Permissions",
        setpermissions_list_actions: "Actions",
        access_list_name: "Name and surname",
        access_list_premission: "Bank Account",
        access_list_actions: "Actions",
        access_list_info: "Has access",
        access_list_button: "Grant access",
        access_set_text: "Select employee",
        access_button_text: "Grant access to your bank account",
        setpermissions_list_nodata: "No additional permissions",
        addemployee_text_idplayer: "Player ID",
        addemployee_placeholder_idplayer: "Enter Player ID",
        addemployee_button_add: "Hire",
        payoutbonus_text_idplayer: "Select Employee",
        payoutbonus_text_hours: "Hours worked",
        payoutbonus_text_money: "To Payout",
        payoutbonus_button_payout: "Pay out bonus",
        dropemployee_text: "Are you sure you want to lay off",
        dropemployee_button_drop: "Lay off",
        changepositionemployee_text_name: "Name and surname",
        changepositionemployee_text_position: "Current position",
        changepositionemployee_text_new_position: "New position",
        changepositionemployee_placeholder_position: "Select new position",
        changepositionemployee_button_save: "Save",
        editposition_placeholder_money: "Earnings per hour",
        editposition_button_save: "Save",
        editpermissions_text_list: "Permissions List",
        editpermissions_text_1: "Issuing invoices",
        editpermissions_text_2: "Account status",
        editpermissions_text_3: "History of financial operations",
        editpermissions_text_4: "Hiring employees",
        editpermissions_text_5: "Paying Bonuses",
        editpermissions_text_6: "Firing employees",
        editpermissions_text_7: "Changing employee position",
        editpermissions_text_8: "Adding ads",
        editpermissions_text_9: "Deleting ads",
        editpermissions_text_10: "Business Statistics",
        editpermissions_text_11: "Purchase upgrades",
        editpermissions_text_12: "Manage bonus amount",
        editpermissions_text_13: "Browse Menu",
        editpermissions_text_15: "Adding menu sets",
        editpermissions_text_16: "Deleting Menu Sets",
        editpermissions_text_17: "Changing employee access",
        editpermissions_button_save: "Save",
        editpermissions_no_permission: "No additional permissions",
        editpermissions_text_permissions: "Position",
        headers_text_finances: "Finance",
        headers_text_employees: "Employees",
        headers_text_announcements: "Announcements",
        headers_text_stats: "Statistics",
        headers_text_updates: "Upgrades",
        headers_text_settings: "Settings",
        headers_text_addInvoice: "Add invoice",
        headers_text_addAnno: "Add an ad",
        headers_text_dropAnno: "Delete ad",
        headers_text_setBonus: "Set bonus amounts",
        headers_text_setMenu: "Set Menu",
        headers_text_setPermissions: "Set employee access",
        headers_text_setAccessBank: "Set access to job bank account",
        headers_text_addEmployee: "Add employee",
        headers_text_payoutBonus: "Pay out bonus",
        headers_text_dropEmployee: "Fire employee",
        headers_text_changePositionEmployee: "Change employee position",
        headers_text_editPosition: "Bonus Edit",
        headers_text_editPermissions: "Edit Permissions",
        headers_text_addNewProduct: "Add Product",
        headers_text_addNewKit: "Add Kit",
        headers_text_dropProduct: "Drop kit",
        restart_timework: "Reset working time",
        headers_text_resetWorktime: "Working time reset",
        editpermissions_text_5_2: "Resetting working time",
        resettimework_text_confirm: "Are you sure you want to reset the working time?",
        resettimework_button_confirm: "Yes, reset",
        // update 29.04
        editpermissions_text_18: "Employee statistics",
        stats_none: "No",
        stats_none2: "Statistics",
        headers_text_employeeStats: "Statistics",
        // update 18.07
        editpermissions_text_19: "Resetting employee statistics",
        stats_reset_button: "Reset statistics",
        // update 04.09
        announcements_button_edit_adv: "Edit",
        headers_text_editAnno: "Edit ad",
        editanno_button: "Save",
    }
}