var questions = {
    ['A']: [
        {
            "questionPhoto": 'question_1.png',
            "question": 'Czy możesz jechać po drodze publicznej w ten sposób?',
            "a": 'Tak, jeśli nie ma innych pojazdów w pobliżu.',
            "b": 'Nie.',
            "c": 'Tak, jeśli jesteś pewny swoich umiejętności.',
            "d": 'Tak, tylko poza obszarami zabudowanymi.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'Zbliżając się do centrum zakrętu, powinieneś',
            "a": 'przesunąć się na zewnątrz zakrętu.',
            "b": 'zmniejszyć manetkę gazu.',
            "c": 'przesunąć się do wewnętrznej strony zakrętu.',
            "d": 'nacisnąć tylny hamulec.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_3.png',
            "question": 'Zbliżając się do skrzyżowania, powinieneś wybrać pozycję na pasie, aby',
            "a": 'zmniejszyć odległość od pojazdu przed Tobą.',
            "b": 'zwiększyć swoją widoczność dla innych kierowców.',
            "c": 'zwiększyć swoją prędkość i szybko przejechać.',
            "d": 'zrobić wszystko, co powyżej.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Jakie są warunki noszenia kasku?',
            "a": 'Noszenie kasku nie jest obowiązkowe podczas jazdy po ulicach miasta.',
            "b": 'Wszyscy motocykliści i pasażerowie muszą zawsze nosić kask.',
            "c": 'Tylko pasażerowie muszą nosić kask.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Chwytanie przedniego hamulca lub blokowanie tylnego hamulca',
            "a": 'Jest najlepszym sposobem zatrzymania się w sytuacji awaryjnej.',
            "b": 'Jest najlepszym sposobem na zwolnienie, gdy ulice są mokre.',
            "c": 'Może zablokować hamulce.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Pasażerowie na motocyklu powinni',
            "a": 'Siedzieć jak najbliżej przodu, nie przeszkadzając kierowcy.',
            "b": 'Kłaść stopy na ziemi, gdy motocykl jest zatrzymany.',
            "c": 'Nie jeździć bez oparcia.',
            "correctAnswer": 'A',
        },
        {
            "question": 'Podczas jazdy w grupie motocyklistów, formacja w jodełkę',
            "a": 'Powinna być używana podczas jazdy w zakrętach.',
            "b": 'Jest zalecana przez cały czas.',
            "c": 'Nie powinna być używana przy wjeździe lub wyjeździe z autostrady.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Powinieneś użyć wyłącznika silnika i ścisnąć sprzęgło, gdy',
            "a": 'Przepustnica jest zablokowana i nie można jej uwolnić.',
            "b": 'Zaczynasz tracić kontrolę w zakręcie.',
            "c": 'Motocykl zaczyna się chwiać.',
            "correctAnswer": 'A',
        },

        {
            "question": 'Przed zmianą pasa ruchu na drodze wielopasmowej, powinieneś sprawdzić',
            "a": 'pas obok ciebie i najdalszy pas.',
            "b": 'tylko najdalszy pas.',
            "c": 'swoje światła sygnalizacyjne.',
            "d": 'tylko pas obok ciebie.',
            "correctAnswer": 'A',
        },
        {
            "question": 'Podczas jazdy w grupie, najlepsza formacja to formacja ___.',
            "a": 'W kształcie Y.',
            "b": 'Bok w bok.',
            "c": 'W jodełkę.',
            "d": 'W kształcie V.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Podczas wykonywania powolnego i ciasnego zakrętu, motocyklista powinien',
            "a": 'pochylać się w przeciwną stronę do motocykla.',
            "b": 'pochylać się do przodu motocykla.',
            "c": 'pochylać się w tym samym kierunku co motocykl.',
            "d": 'utrzymywać ciało prosto, pochylając tylko motocykl.',
            "correctAnswer": 'D',
        },
        {
            "question": 'Jeśli jest ruch z naprzeciwka i wyprzedzasz szereg zaparkowanych samochodów, którą pozycję na pasie powinieneś wybrać?',
            "a": 'Środek',
            "b": 'Prawa',
            "c": 'Środek lub prawa',
            "d": 'Lewa',
            "correctAnswer": 'A',
        },
        {
            "question": 'Większość mocy hamowania twojego motocykla jest dostarczana przez',
            "a": 'tylny hamulec.',
            "b": 'przednie i tylne hamulce w równym stopniu.',
            "c": 'sprzęgło.',
            "d": 'przedni hamulec.',
            "correctAnswer": 'D',
        },
        {
            "question": 'Jeśli twój motocykl zaczyna się chwiać, najlepszą rzeczą do zrobienia jest',
            "a": 'szybkie hamowanie.',
            "b": 'stopniowe zamknięcie przepustnicy.',
            "c": 'mocne chwycenie kierownicy i pokonanie chwiania.',
            "d": 'przyspieszenie, aby wyjść z chwiania.',
            "correctAnswer": 'C',
        },
        {
            "question": "Powierzchnie, które oferują niewielką przyczepność dla motocykla, obejmują",
            "a": 'mało uczęszczane drogi.',
            "b": 'drogi żwirowe.',
            "c": 'ślady opon, gdzie jechały inne pojazdy.',
            "d": 'nawierzchnia rozgrzana od słońca.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Zwiększ swoje bezpieczeństwo w nocy poprzez',
            "a": 'korzystanie ze świateł samochodu przed Tobą, aby lepiej widzieć.',
            "b": 'zwiększenie swojej odległości od pojazdu przed Tobą.',
            "c": 'jazdę z włączonymi światłami drogowymi.',
            "d": 'robienie wszystkiego, co powyżej.',
            "correctAnswer": 'D',
        },
        {
            "question": 'Podążając za pojazdem, powinieneś utrzymywać odległość wynoszącą ___ sekund.',
            "a": 'dwie',
            "b": 'trzy',
            "c": 'cztery',
            "d": 'pięć',
            "correctAnswer": 'A',
        },
        {
            "question": 'Ile pozycji na pasie ma motocykl w pasie ruchu?',
            "a": '1',
            "b": '2',
            "c": '3',
            "d": '4',
            "correctAnswer": 'C',
        },
    ],
    ['B']: [
        {
            "questionPhoto": 'question_1.png',
            "question": 'Czy należy hamować w takiej sytuacji?',
            "a": 'Tak, ponieważ jest wystarczająca odległość do hamowania.',
            "b": 'Nie, ponieważ za chwilę światło zmieni się na zielone.',
            "c": 'Nie.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'Czy możesz zatrzymać się na tej części chodnika?',
            "a": 'Tak, ale tylko wtedy, gdy zatrzyma nas policja.',
            "b": 'Tak.',
            "c": 'Tak, maksymalnie na 5 minut.',
            "d": 'Nie.',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": 'question_3.png',
            "question": 'Czy możesz skręcić w lewo w tej sytuacji?',
            "a": 'Tak.',
            "b": 'Nie.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_4.png',
            "question": 'Czy możesz skręcić w prawo w tym punkcie bez zatrzymywania się?',
            "a": 'Tak, kiedy pojazdy nie nadjeżdżają z lewej strony.',
            "b": 'Nie, znak nakazuje bezwzględne zatrzymanie pojazdu.',
            "c": 'Tak, ten znak oznacza moją pierwszeństwo.',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_5.png',
            "question": 'Jaka jest maksymalna prędkość, jaką możesz jechać na tej drodze?',
            "a": '140 km/h',
            "b": '110 km/h',
            "c": '120 km/h',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_6.png',
            "question": 'Czy droga pokazana na zdjęciu może być przejeżdżana w obu kierunkach?',
            "a": 'Tak, jeśli nie zagraża to bezpieczeństwu innych uczestników ruchu.',
            "b": 'Nie.',
            "c": 'Tak.',
            "d": 'Tylko taksówki mogą jechać w przeciwnym kierunku.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_7.png',
            "question": 'Czy możesz skręcić w lewo w tym miejscu?',
            "a": 'Tak.',
            "b": 'Nie.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": 'question_8.png',
            "question": 'Które z tych oznaczeń na jezdni oddziela dwa pasy ruchu poruszające się w tym samym kierunku?',
            "a": 'A',
            "b": 'B',
            "c": 'Żadne z powyższych',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_9.png',
            "question": 'Ten znak oznacza:',
            "a": 'Przejście dla pieszych przed Tobą',
            "b": 'Piesi nie mogą tu przechodzić',
            "c": 'Piesi idący wzdłuż drogi przed Tobą',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_10.png',
            "question": 'Ten znak oznacza:',
            "a": 'Zakaz wjazdu.',
            "b": 'Parking zarezerwowany dla osób niepełnosprawnych.',
            "c": 'Ustąp pierwszeństwa.',
            "correctAnswer": 'A',
        },
        {
            "question": 'Czy możesz wyprzedzać inny pojazd zbliżając się do zakrętu lub wzniesienia?',
            "a": 'Tak, ale możesz wyprzedzać tylko z prawej strony.',
            "b": 'Nie, nigdy.',
            "c": 'Tak, ale tylko jeśli jest wystarczająco dużo miejsca.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Które z poniższych miejsc jest dozwolone na zawracanie?',
            "a": 'Na przejeździe kolejowym',
            "b": 'Przez podwójną żółtą linię',
            "c": 'Na ulicy jednokierunkowej',
            "correctAnswer": 'B',
        },
        {
            "question": 'Powinieneś zmniejszyć prędkość o połowę, gdy droga jest ___.',
            "a": 'mokra',
            "b": 'oblodzona',
            "c": 'pokryta śniegiem',
            "correctAnswer": 'C',
        },
        {
            "question": 'Podczas jazdy we mgle, deszczu lub śniegu używaj ___.',
            "a": 'świateł mijania',
            "b": 'tylko świateł przeciwmgielnych',
            "c": 'świateł drogowych',
            "correctAnswer": 'A',
        },
        {
            "question": 'Przerywana żółta linia środkowa oznacza, że:',
            "a": 'Wyprzedzanie nie jest dozwolone.',
            "b": 'Wyprzedzanie z lewej strony jest dozwolone, gdy droga jest wolna.',
            "c": 'Wyprzedzanie z prawej strony jest dozwolone, gdy droga jest wolna.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Alkohol to',
            "a": 'Stymulant.',
            "b": 'Fajny',
            "c": 'Depresant.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Przed zmianą pasa ruchu powinieneś sprawdzić swoje lusterka i',
            "a": 'Spojrzeć przez ramię',
            "b": 'Nigdy nie patrzeć przez prawe ramię',
            "c": 'Zawsze zwolnić na swoim pasie ruchu',
            "correctAnswer": 'A',
        },
        
    ],
    ['C']: [
        {
            "question": 'Której z poniższych czynności NIE powinieneś wykonywać, jeśli napotkasz awarię opony?',
            "a": 'Bądź świadomy, że opona jest uszkodzona.',
            "b": 'Hamuj mocno i natychmiast.',
            "c": 'Trzymaj kierownicę mocno.',
            "d": 'Nie dotykaj pedału hamulca.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Flagi lub światła są wymagane na ładunkach wystających, które wystają',
            "a": '56 cali lub więcej poza tył pojazdu.',
            "b": '3 stopy lub więcej poza tył pojazdu.',
            "c": '4 stopy lub więcej poza tył pojazdu.',
            "d": '6 stóp lub więcej poza tył pojazdu.',
            "correctAnswer": 'C',
        },
        {
            "question": 'Która z tych wartości odpowiada całkowitej odległości hamowania?',
            "a": 'Odległość reakcji + odległość hamowania',
            "b": 'Odległość reakcji + odległość hamowania + odległość sygnału',
            "c": 'Odległość postrzegania + odległość reakcji + odległość hamowania',
            "d": 'Odległość postrzegania + odległość reakcji',
            "correctAnswer": 'C',
        },
        {
            "question": 'Aby pomóc zachować czujność i bezpieczeństwo podczas jazdy, powinieneś',
            "a": 'pić kawę, jeśli jesteś senny.',
            "b": 'unikać leków, których etykiety ostrzegają przed sennością.',
            "c": 'wypić whisky, aby się przygotować.',
            "d": 'otworzyć okna, aby zaczerpnąć powietrza.',
            "correctAnswer": 'B',
        },
        {
            "question": 'Gaśnica typu A : B : C jest przeznaczona do pracy w jakich typach pożarów?',
            "a": 'Drewno, papier i tkaniny',
            "b": 'Benzyna',
            "c": 'Elektryczny',
            "d": 'Wszystkie powyższe',
            "correctAnswer": 'D',
        },
    ],
}
