Config = {}
Config.Spawn = vector4(-412.15139770508, 1172.0770263672, 325.80334472656-1.35, 162.42915344238)

RegisterCommand = function()

end
lib.addCommand = function()

end
ESX.RegisterCommand = function()

end
Config.Buttons = {
    ["creator"] = {
        {
            name = "identity",
            label = "Tożsamość",
            isActive = true
        }
    },
}

Config.Components = {
}

Config.ResetElement = {
	["tshirt_1"] = "tshirt_2",
	["torso_1"] = "torso_2",
	["decals_1"] = "decals_2",
	["arms"] = "arms_2",
	["pants_1"] = "pants_2",
	["shoes_1"] = "shoes_2",
	["mask_1"] = "mask_2",
	["bproof_1"] = "bproof_2",
	["chain_1"] = "chain_2",
	["helmet_1"] = "helmet_2",
	["glasses_1"] = "glasses_2",
	["watches_1"] = "watches_2",
	["bracelets_1"] = "bracelets_2",
	["bags_1"] = "bags_2",
	["ears_1"] = "ears_2",
}

Config.TattooButtons = {
    { name = "ZONE_TORSO", label = "Tułów" },
    { name = "ZONE_HEAD", label = "Głowa" },
    { name = "ZONE_LEFT_ARM", label = "Lewa Ręka" },
    { name = "ZONE_RIGHT_ARM", label = "Prawa Ręka" },
    { name = "ZONE_LEFT_LEG", label = "Lewa Noga" },
    { name = "ZONE_RIGHT_LEG", label = "Prawa Noga" },
    { name = "ZONE_NONE", label = "Inne" }
}

Config.TattooList = {
    { category = "ZONE_TORSO", label = "Demoniczny jeździec", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_000_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Dwie lufy", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_001_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Hołd róży", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_002_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Jeździec w sieci", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_003_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Gniew smoka", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_004_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Prosto z Ameryki", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_005_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Motocyklowa wolność", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_006_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Pikujący orzeł", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_007_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Koło wolności", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_008_M", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Makabryczny pająk", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_009_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bycza czaszka", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_010_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Pokój braciom", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_011_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Miejski kaskader", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_012_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Kości demona", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_013_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Statua Śmiertelności", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_014_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Krzyż na drogę", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_015_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Makabryczne drzewo", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_016_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Szponiasta bestia", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_017_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Kościany motor", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_018_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Straszliwe szpony", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_019_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Róża i czaszka", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_020_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Płonący żniwiarz", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_021_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Logo Western", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_022_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Western MC", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_023_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Jazda po kres", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_024_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Powodzenia", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_025_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Amerykański sen", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_026_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Pech", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_027_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Jeździec zmroku", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_028_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Kościany klucz", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_029_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bracia aż po grób", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_030_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Spaliniarz", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_031_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Orzeł Western", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_032_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Emblemat orła", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_033_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bractwo motocykli", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_034_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Łańcuchowa piącha", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_035_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Pochłonięta czacha", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_036_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Wypalona dusza", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_037_M", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "FTW", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_038_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Nienasycony żłopacz", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_039_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Amerykańskiej roboty", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_040_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bez żalu", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_041_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Ponury jeździec", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_042_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Wieczna jazda", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_043_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Nieskrępowana jazda", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_044_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Ostra jazda, szybka śmierć", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_045_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Łańcuch z czachą", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_046_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Wężowa maszyna", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_047_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "STFU", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_048_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Te barwy nie wymiękają", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_049_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bez wybaczenia", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_050_M", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Stylizowane Western", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_051_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Jeleni wieniec", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_052_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Kask", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_053_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Mama", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_054_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Jadowity skorpion", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_055_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Trupi motocykl", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_056_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Wesoła czacha", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_057_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Sępia kostucha", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_058_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Faggio", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_059_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Jesteśmy Modsami!", collection = "mpbiker_overlays", name = "MP_MP_Biker_Tat_060_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Szturm SA", collection = "mplowrider2_overlays", name = "MP_LR_Tat_000_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Kobieta wamp", collection = "mplowrider2_overlays", name = "MP_LR_Tat_003_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Zawirowania miłości", collection = "mplowrider2_overlays", name = "MP_LR_Tat_006_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Miłość do gry", collection = "mplowrider2_overlays", name = "MP_LR_Tat_008_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Pani Wolność", collection = "mplowrider2_overlays", name = "MP_LR_Tat_011_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Królewski pocałunek", collection = "mplowrider2_overlays", name = "MP_LR_Tat_012_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Dwie twarze", collection = "mplowrider2_overlays", name = "MP_LR_Tat_016_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Impreza szkieletów", collection = "mplowrider2_overlays", name = "MP_LR_Tat_018_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Zamaskowana śmierć", collection = "mplowrider2_overlays", name = "MP_LR_Tat_019_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Moje szalone życie", collection = "mplowrider2_overlays", name = "MP_LR_Tat_022_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Miłość Los Muertos", collection = "mplowrider2_overlays", name = "MP_LR_Tat_028_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Do grobowej deski", collection = "mplowrider2_overlays", name = "MP_LR_Tat_029_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Gracz San Andreas", collection = "mplowrider2_overlays", name = "MP_LR_Tat_030_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Zabójcze piękno", collection = "mplowrider2_overlays", name = "MP_LR_Tat_031_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Władza", collection = "mplowrider2_overlays", name = "MP_LR_Tat_032_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Czarne łzy", collection = "mplowrider2_overlays", name = "MP_LR_Tat_035_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Jeździec czach", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_000", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Pająk - kontur", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_001", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Wąż - kontur", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_003", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Wąż - cieniowany", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_004", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Karp - kontur", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_005", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Karp - cieniowany", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_006", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Los Muertos", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_007", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Lepsza śmierć niż hańba", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_008", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Czas umierać", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_009", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Elektryczny wąż", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_010", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Tygrysi ryk", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_011", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Bila z czachą", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_012", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Jaszczurka", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_013", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Kwiecisty sztylet", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_014", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Japoński wojownik", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_015", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Tonący okręt - kontur", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_016", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Tonący okręt - kolor", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_017", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Królewski sztylet - kontur", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_018", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Królewski sztylet - kolor", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_019", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Teraz ty - kontur", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_022", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Teraz ty - kolor", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_023", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Głowa węża - kontur", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_024", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Głowa węża - kolor", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_025", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Jebitny fart - kontur", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_026", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Jebitny fart - kolor", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_027", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Kat", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_028", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Piękna śmierć", collection = "mpchristmas2_overlays", name = "MP_Xmas2_M_Tat_029", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Kasiora rządzi", collection = "mpbusiness_overlays", name = "MP_Buis_M_Neck_000", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Pogrubiony dolar", collection = "mpbusiness_overlays", name = "MP_Buis_M_Neck_001", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Pochylony dolar", collection = "mpbusiness_overlays", name = "MP_Buis_M_Neck_002", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "$100", collection = "mpbusiness_overlays", name = "MP_Buis_M_Neck_003", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Studolarówka", collection = "mpbusiness_overlays", name = "MP_Buis_M_LeftArm_000", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Wszystkowidzące oko", collection = "mpbusiness_overlays", name = "MP_Buis_M_LeftArm_001", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Dolarowa czacha", collection = "mpbusiness_overlays", name = "MP_Buis_M_RightArm_000", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Zielone", collection = "mpbusiness_overlays", name = "MP_Buis_M_RightArm_001", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Stylowy kozak", collection = "mpbusiness_overlays", name = "MP_Buis_M_Stomach_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bogacz", collection = "mpbusiness_overlays", name = "MP_Buis_M_Chest_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "$$$", collection = "mpbusiness_overlays", name = "MP_Buis_M_Chest_001", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Koszenie hajsu", collection = "mpbusiness_overlays", name = "MP_Buis_M_Back_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Wysokie stawki", collection = "mpbusiness_overlays", name = "MP_Buis_F_Chest_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Trzepanie kasy", collection = "mpbusiness_overlays", name = "MP_Buis_F_Chest_001", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Kocham szmal", collection = "mpbusiness_overlays", name = "MP_Buis_F_Chest_002", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Diamentowy", collection = "mpbusiness_overlays", name = "MP_Buis_F_Stom_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Logo Santo Capra", collection = "mpbusiness_overlays", name = "MP_Buis_F_Stom_001", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Worek pieniędzy", collection = "mpbusiness_overlays", name = "MP_Buis_F_Stom_002", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Szacun", collection = "mpbusiness_overlays", name = "MP_Buis_F_Back_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Blachara", collection = "mpbusiness_overlays", name = "MP_Buis_F_Back_001", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Logo Val-de-Grace", collection = "mpbusiness_overlays", name = "MP_Buis_F_Neck_000", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Róża z banknotów", collection = "mpbusiness_overlays", name = "MP_Buis_F_Neck_001", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Symbol dolara", collection = "mpbusiness_overlays", name = "MP_Buis_F_RArm_000", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Nie ma jak chciwość", collection = "mpbusiness_overlays", name = "MP_Buis_F_LArm_000", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Jedynka", collection = "mpbusiness_overlays", name = "MP_Buis_F_LLeg_000", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Diamentowa korona", collection = "mpbusiness_overlays", name = "MP_Buis_F_RLeg_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Skrzyżowane strzały", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_000", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Pojedyncza strzała", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_001", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Chemia", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_002", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Diamentowy blask", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_003", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Kość", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_004", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Piękne oko", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_005", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Ptasie pióro", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_006", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Cegły", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_007", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Sześcian", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_008", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Kwadraty", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_009", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Podkowa", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_010", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Nieskończoność", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_011", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Rogi", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_012", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Boombox", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_013", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Puszka z farbą", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_014", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Wąsy", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_015", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Piorun", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_016", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Urok", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_019", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Geometryczny lis", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_021", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Uśmiech", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_023", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Piramida", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_024", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Patrz pod nogi", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_025", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Pizza", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_026", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Ciernista róża", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_028", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Smutas", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_029", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Płetwa rekina", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_030", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Deska", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_031", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Papierowy samolot", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_032", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Rogacz", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_033", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Stop", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_034", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Zszyte serce", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_035", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Kształty", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_036", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Wschód", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_037", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Larwa", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_038", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Rękaw", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_039", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Czarna kotwica", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_040", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Ząb", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_041", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Świeca zapłonowa", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_042", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Biały trójkąt", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_043", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Czarny trójkąt", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_044", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Kolczuga", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_045", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Trójkąty", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_046", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Kaseta", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_047", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Pokój", collection = "mphipster_overlays", name = "FM_Hip_M_Tat_048", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_001_a", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_001_b", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_001_c", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_001_d", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_001_e", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_003_a", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_003_b", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_003_c", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_003_d", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_003_e", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_006_a", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_006_b", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_006_c", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_006_d", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_006_e", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_008_a", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_008_b", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_008_c", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_008_d", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_008_e", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_long_a", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_long_b", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_long_c", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_long_d", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "FM_M_Hair_long_e", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_001", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_002", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_003", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_004", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_005", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_006", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_007", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_008", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_009", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_010", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_011", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_012", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_013", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_014", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NG_M_Hair_015", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NGBea_M_Hair_000", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NGBea_M_Hair_001", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NGBus_M_Hair_000", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NGBus_M_Hair_001", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NGHip_M_Hair_000", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NGHip_M_Hair_001", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Hair", collection = "multiplayer_overlays", name = "NGInd_M_Hair_000", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "XX Emoji", collection = "vms_overlays", name = "MP_VMS_FACE_000", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Libery", collection = "vms_overlays", name = "MP_VMS_FACE_001", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "R.I.P. XXX", collection = "vms_overlays", name = "MP_VMS_FACE_002", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "XX Emoji 2", collection = "vms_overlays", name = "MP_VMS_FACE_003", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Broken Heart", collection = "vms_overlays", name = "MP_VMS_FACE_004", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "666", collection = "vms_overlays", name = "MP_VMS_FACE_005", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Lover", collection = "vms_overlays", name = "MP_VMS_FACE_006", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Kiss", collection = "vms_overlays", name = "MP_VMS_FACE_007", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Playboy", collection = "vms_overlays", name = "MP_VMS_FACE_008", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Sparkles", collection = "vms_overlays", name = "MP_VMS_FACE_009", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "V-ictory", collection = "vms_overlays", name = "MP_VMS_FACE_010", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Beast", collection = "vms_overlays", name = "MP_VMS_FACE_011", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Gun", collection = "vms_overlays", name = "MP_VMS_FACE_012", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Cross", collection = "vms_overlays", name = "MP_VMS_FACE_013", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Dagger on Eye", collection = "vms_overlays", name = "MP_VMS_FACE_014", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Dagger at Right", collection = "vms_overlays", name = "MP_VMS_FACE_015", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Spider", collection = "vms_overlays", name = "MP_VMS_FACE_016", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Heart Outline", collection = "vms_overlays", name = "MP_VMS_FACE_017", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Tear", collection = "vms_overlays", name = "MP_VMS_FACE_018", price = 500, removePrice = 750 },
    { category = "ZONE_NONE", label = "Wings", collection = "vms_overlays", name = "MP_VMS_NECK_001", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Waleczni królowie", collection = "mplowrider_overlays", name = "MP_LR_Tat_001_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Święta Maria", collection = "mplowrider_overlays", name = "MP_LR_Tat_002_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Mikrofon-spluwa", collection = "mplowrider_overlays", name = "MP_LR_Tat_004_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Bez zła", collection = "mplowrider_overlays", name = "MP_LR_Tat_005_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Wąż LS", collection = "mplowrider_overlays", name = "MP_LR_Tat_007_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Amazonka", collection = "mplowrider_overlays", name = "MP_LR_Tat_009_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Zły anioł", collection = "mplowrider_overlays", name = "MP_LR_Tat_010_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Miłosna ruletka", collection = "mplowrider_overlays", name = "MP_LR_Tat_013_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Ślepa miłość", collection = "mplowrider_overlays", name = "MP_LR_Tat_014_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Uwodzicielka", collection = "mplowrider_overlays", name = "MP_LR_Tat_015_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Pomaluj mnie", collection = "mplowrider_overlays", name = "MP_LR_Tat_017_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Prezydenci", collection = "mplowrider_overlays", name = "MP_LR_Tat_020_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Smutny anioł", collection = "mplowrider_overlays", name = "MP_LR_Tat_021_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Taniec serc", collection = "mplowrider_overlays", name = "MP_LR_Tat_023_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Królewskie przejęcie", collection = "mplowrider_overlays", name = "MP_LR_Tat_026_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Życie w Los Santos", collection = "mplowrider_overlays", name = "MP_LR_Tat_027_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Miejski smutek", collection = "mplowrider_overlays", name = "MP_LR_Tat_033_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Turbulencje", collection = "mpairraces_overlays", name = "MP_Airraces_Tattoo_000_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Czaszka pilota", collection = "mpairraces_overlays", name = "MP_Airraces_Tattoo_001_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Uskrzydlona bomba", collection = "mpairraces_overlays", name = "MP_Airraces_Tattoo_002_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Toksyczny ślad", collection = "mpairraces_overlays", name = "MP_Airraces_Tattoo_003_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Pionier balonów", collection = "mpairraces_overlays", name = "MP_Airraces_Tattoo_004_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Piękność na spadochronie", collection = "mpairraces_overlays", name = "MP_Airraces_Tattoo_005_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bombardowanie", collection = "mpairraces_overlays", name = "MP_Airraces_Tattoo_006_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "W zasięgu wzroku orła", collection = "mpairraces_overlays", name = "MP_Airraces_Tattoo_007_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Blok silnika", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_000_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Pełna moc", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_001_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Tuning aż po grób", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_002_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Mechaniczny rękaw", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_003_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Tłokowy rękaw", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_004_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Pełne skupienie", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_005_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Silnik w ogniu", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_006_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Wieczna jazda", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_007_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Scarlett", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_008_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Węże zagłady", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_009_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bycza kierownica", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_010_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Uważaj na słowa", collection = "mpimportexport_overlays", name = "MP_MP_ImportExport_Tat_011_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Kuloodporny", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_000_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Skrzyżowana broń", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_001_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Granat", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_002_M", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Broń w pogotowiu", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_003_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Broń przyboczna", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_004_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Patriotyczna czacha", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_005_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Bojowa czacha", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_006_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Stylizowany tygrys", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_007_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Pas na amunicję", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_008_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Nóż motylkowy", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_009_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Władza pieniądza", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_010_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Czaszka śmierci", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_011_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Dolarowe sztylety", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_012_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Znak wilka", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_013_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Kosa w plecy", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_014_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Nabita czacha", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_015_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Krwawa forsa", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_016_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Nieśmiertelniki", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_017_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Dwulufowa czaszka", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_018_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Uskrzydlone pistolety", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_019_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Bronie z koroną", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_020_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Miłego dnia", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_021_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Wybuchowe serce", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_022_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Różany rewolwer", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_023_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Bojowy żniwiarz", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_024_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Modlitwa czaszki", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_025_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Niespokojna czaszka", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_026_M", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Wężowy rewolwer", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_027_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Łańcuch SMG", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_028_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Raz sukces, raz porażka", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_029_M", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Pistoletowy as", collection = "mpgunrunning_overlays", name = "MP_Gunrunning_Tattoo_030_M", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Liny statku", collection = "mpbeach_overlays", name = "MP_Bea_M_Back_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Plemienny rekin młot", collection = "mpbeach_overlays", name = "MP_Bea_M_Chest_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Plemienny rekin", collection = "mpbeach_overlays", name = "MP_Bea_M_Chest_001", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Piracka czaszka", collection = "mpbeach_overlays", name = "MP_Bea_M_Head_000", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_LEG", label = "Plemienna gwiazda", collection = "mpbeach_overlays", name = "MP_Bea_M_Lleg_000", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_LEG", label = "Plemienna wieża Tiki", collection = "mpbeach_overlays", name = "MP_Bea_M_Rleg_000", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Plemienne słońce", collection = "mpbeach_overlays", name = "MP_Bea_M_RArm_000", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Wieża Tiki", collection = "mpbeach_overlays", name = "MP_Bea_M_LArm_000", price = 500, removePrice = 750 },
    { category = "ZONE_LEFT_ARM", label = "Syrena Los Santos", collection = "mpbeach_overlays", name = "MP_Bea_M_LArm_001", price = 500, removePrice = 750 },
    { category = "ZONE_HEAD", label = "Surfing", collection = "mpbeach_overlays", name = "MP_Bea_M_Neck_001", price = 500, removePrice = 750 },
    { category = "ZONE_RIGHT_ARM", label = "Piękność z Vespucci", collection = "mpbeach_overlays", name = "MP_Bea_M_RArm_001", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Miecznik", collection = "mpbeach_overlays", name = "MP_Bea_M_Stom_000", price = 500, removePrice = 750 },
    { category = "ZONE_TORSO", label = "Koło", collection = "mpbeach_overlays", name = "MP_Bea_M_Stom_001", price = 500, removePrice = 750 }
}